### ISSUE TITLE
可以训练，但在python test.py时，出错

### ISSUE THREAD

**Issue by qinzhuoxing** [qiaochen/DDPG_MultiAgent#2]
E0310 17:03:28.927829591    9681 server_chttp2.cc:40]        {"created":"@1552208608.927765594","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":307,"referenced_errors":[{"created":"@1552208608.927759359","description":"Failed to add any wildcard listeners","file":"src/core/lib/iomgr/tcp_server_posix.cc","file_line":345,"referenced_errors":[{"created":"@1552208608.927747822","description":"Unable to configure socket","fd":8,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":202,"referenced_errors":[{"created":"@1552208608.927743023","description":"OS Error","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":175,"os_error":"Address already in use","syscall":"bind"}]},{"created":"@1552208608.927758651","description":"Unable to configure socket","fd":8,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":202,"referenced_errors":[{"created":"@1552208608.927756107","description":"OS Error","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":175,"os_error":"Address already in use","syscall":"bind"}]}]}]}
Found path: /home/qzx/文档/DDPG_MultiAgent-master/./Tennis_Linux/Tennis.x86_64
Mono path[0] = '/home/qzx/文档/DDPG_MultiAgent-master/./Tennis_Linux/Tennis_Data/Managed'
Mono config path = '/home/qzx/文档/DDPG_MultiAgent-master/./Tennis_Linux/Tennis_Data/MonoBleedingEdge/etc'
Preloaded 'ScreenSelector.so'
Preloaded 'libgrpc_csharp_ext.x64.so'
Unable to preload the following plugins:
	ScreenSelector.so
	libgrpc_csharp_ext.x86.so
Logging to /home/qzx/.config/unity3d/Unity Technologies/Unity Environment/Player.log
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    env = UnityEnvironment(file_name=unity_environment_path)
  File "/home/qzx/.local/lib/python3.5/site-packages/unityagents/environment.py", line 64, in __init__
    aca_params = self.send_academy_parameters(rl_init_parameters_in)
  File "/home/qzx/.local/lib/python3.5/site-packages/unityagents/environment.py", line 505, in send_academy_parameters
    return self.communicator.initialize(inputs).rl_initialization_output
  File "/home/qzx/.local/lib/python3.5/site-packages/unityagents/rpc_communicator.py", line 60, in initialize
    "The Unity environment took too long to respond. Make sure that :\n"
unityagents.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Academy and the External Brain(s) are attached to objects in the Scene
	 The environment and the Python interface have compatible versions.

感谢！！！

**Comment by qiaochen** [comment]
在launch Unity的时候我发现有这段报错，"...Address already in use..."
也许是后台server地址已经被占用了？确保地址释放后，再尝试执行一下？
